CREATE TABLE part_external_offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id BIGINT NOT NULL REFERENCES parts(id),
  source VARCHAR(100) NOT NULL,
  search_query VARCHAR(255) NOT NULL,
  title VARCHAR(500),
  image_url TEXT,
  supplier_name VARCHAR(255),
  offer_url TEXT,
  low_price INTEGER,
  raw_payload JSONB,
  refreshed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_part_external_offers_low_price CHECK (low_price IS NULL OR low_price >= 0)
);

CREATE UNIQUE INDEX ux_part_external_offers_part_source_active
  ON part_external_offers(part_id, source)
  WHERE deleted_at IS NULL;

CREATE INDEX idx_part_external_offers_part_id ON part_external_offers(part_id);
CREATE INDEX idx_part_external_offers_source ON part_external_offers(source);
CREATE INDEX idx_part_external_offers_refreshed_at ON part_external_offers(refreshed_at);
CREATE INDEX idx_part_external_offers_deleted_at ON part_external_offers(deleted_at);
