CREATE TABLE part_catalog_refresh_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  source VARCHAR(100) NOT NULL,
  category VARCHAR(50) NOT NULL,
  search_query VARCHAR(255) NOT NULL,
  status VARCHAR(30) NOT NULL,
  attempted_count INTEGER NOT NULL DEFAULT 0,
  discovered_count INTEGER NOT NULL DEFAULT 0,
  published_count INTEGER NOT NULL DEFAULT 0,
  error_summary TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_part_catalog_refresh_jobs_category CHECK (category IN ('CPU', 'GPU', 'RAM', 'MOTHERBOARD', 'STORAGE', 'PSU', 'CASE', 'COOLER')),
  CONSTRAINT chk_part_catalog_refresh_jobs_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED'))
);

CREATE INDEX idx_part_catalog_refresh_jobs_category ON part_catalog_refresh_jobs(category);
CREATE INDEX idx_part_catalog_refresh_jobs_status ON part_catalog_refresh_jobs(status);
CREATE INDEX idx_part_catalog_refresh_jobs_started_at ON part_catalog_refresh_jobs(started_at);
CREATE INDEX idx_part_catalog_refresh_jobs_deleted_at ON part_catalog_refresh_jobs(deleted_at);

CREATE TABLE part_catalog_candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  refresh_job_id BIGINT REFERENCES part_catalog_refresh_jobs(id),
  published_part_id BIGINT REFERENCES parts(id),
  source VARCHAR(100) NOT NULL,
  category VARCHAR(50) NOT NULL,
  source_product_key VARCHAR(500) NOT NULL,
  search_query VARCHAR(255) NOT NULL,
  title VARCHAR(500) NOT NULL,
  manufacturer_guess VARCHAR(100),
  image_url TEXT,
  supplier_name VARCHAR(255),
  offer_url TEXT,
  low_price INTEGER,
  candidate_status VARCHAR(30) NOT NULL DEFAULT 'DISCOVERED',
  raw_payload JSONB,
  discovered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ,
  deleted_at TIMESTAMPTZ,
  CONSTRAINT chk_part_catalog_candidates_category CHECK (category IN ('CPU', 'GPU', 'RAM', 'MOTHERBOARD', 'STORAGE', 'PSU', 'CASE', 'COOLER')),
  CONSTRAINT chk_part_catalog_candidates_status CHECK (candidate_status IN ('DISCOVERED', 'PUBLISHED', 'REJECTED')),
  CONSTRAINT chk_part_catalog_candidates_low_price CHECK (low_price IS NULL OR low_price >= 0)
);

CREATE UNIQUE INDEX ux_part_catalog_candidates_source_product_active
  ON part_catalog_candidates(source, category, source_product_key)
  WHERE deleted_at IS NULL;

CREATE INDEX idx_part_catalog_candidates_category ON part_catalog_candidates(category);
CREATE INDEX idx_part_catalog_candidates_status ON part_catalog_candidates(candidate_status);
CREATE INDEX idx_part_catalog_candidates_refresh_job_id ON part_catalog_candidates(refresh_job_id);
CREATE INDEX idx_part_catalog_candidates_published_part_id ON part_catalog_candidates(published_part_id);
CREATE INDEX idx_part_catalog_candidates_last_seen_at ON part_catalog_candidates(last_seen_at);
CREATE INDEX idx_part_catalog_candidates_deleted_at ON part_catalog_candidates(deleted_at);
